### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by moshedoppelt** [aligoren/SecurePasswordGenerator#2]
if you double click the title in the "password list"
it genetate an error in the passwordList.cs

**Comment by aligoren** [comment]
Hi. Thanks for your feedback. Where is the error?20.09.2016, 15:27, "moshedoppelt" <notifications@github.com>:if you double click the title in the "password list"
it genetate an error in the passwordList.cs

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Yours sincerely, Ali GOREN

**Comment by moshedoppelt** [comment]
on line 53 
string rowCustomPassword = dgvPasswordList.Rows[e.RowIndex].Cells["CustomPassword"].Value.ToString();

**Comment by aligoren** [comment]
@moshedoppelt Thanks your feedback. I solved :)

**Comment by aligoren** [comment]
@moshedoppelt Thanks for your feedback.  solved: check 8e422eff5a96986c8c443292e0c9633e5f5fcbcf
